### ISSUE TITLE
binding fail

### ISSUE THREAD

**Issue by dragutux** [SpaceMadness/lunar-unity-plugin#5]
hi, so no matter what key to what command i try, i cannot apparently map to keys, i'm using unity 5, it write configs fine, i can execute commands from the terminal, but the binding does not work :/

**Comment by dragutux** [comment]
forgot : tried on stealth & angry bot project : downloaded them from here.

**Comment by GH-AlexL** [comment]
Hey there. Sure, I'll take a look.

**Comment by dragutux** [comment]
i have skype; i am live on livecoding if you want, i am doing this live and i can share screen, i got a mic, this is being checked / tested on livecoding.tv/dragutux :) (also on twitch.tv/dragutux) i am more than willing to do anything as i love this plugin! :D

**Comment by dragutux** [comment]
(skype : same name as here, dragutux everywhere :P)

**Comment by GH-AlexL** [comment]
That's great! You can try to debug the issue and send me a pull request :)

**Comment by dragutux** [comment]
video where i work on this : https://www.livecoding.tv/dragutux/videos/M5ANK-gamedev-545-working-on-game-name-3 binding work all on it or almost all (some previous testing is in another video, all videos are accessible at https://www.livecoding.tv/dragutux/videos/ the series where i do this is "5/45")

**Comment by dragutux** [comment]
i tried debuguing it, i have no idea where to see where the input is read & then assigned...

**Comment by dragutux** [comment]
i'm up for a debug session on skype for example or whatever ^^

**Comment by dragutux** [comment]
it writes bind, no idea if a single command without space can be binded, testing this with the rogue test which has single commands

**Comment by GH-AlexL** [comment]
I'm still at work and can't do much right now. Did you check the "binding" section on the wiki?

https://github.com/SpaceMadness/lunar-unity-plugin/wiki/Key-Binding

**Comment by dragutux** [comment]
yes i did, which validated the binding were read..

**Comment by dragutux** [comment]
out of crazyness i even switched my keyboard in qwerty even ^^

**Comment by dragutux** [comment]
made a specific test, stopping stream quickly to create specific video, linking it in a few.

**Comment by GH-AlexL** [comment]
This should work:

bind <shortcut> [<command>]

If it doesn't - that's a bug. I can take a look in an hour or two

**Comment by dragutux** [comment]
![hereisthefuck](https://cloud.githubusercontent.com/assets/5103764/13481064/c8f36006-e0e2-11e5-98f7-f81bdc42c847.png)

**Comment by dragutux** [comment]
bind files also : 

![thebindfileplaymode](https://cloud.githubusercontent.com/assets/5103764/13481124/39e73738-e0e3-11e5-9fef-eee48ab7e82a.png)

![thebindfiledefault](https://cloud.githubusercontent.com/assets/5103764/13481146/62639f44-e0e3-11e5-9cb3-73208325335e.png)

**Comment by dragutux** [comment]
and none works and your command says there's no bindings :) i don't have enough experience of this project (where it reads store etc) to find the problem tho it's either captions or capture, bindlist returns my commands so the problem is maybe capturing input i dont know, unity5 :D i use default project commands..

again, can we call from script ? because on an Update i can catch a key event and call a function so..
that'll solve gameplay implementation also :) binding is better of course as i have numerous trigger ideas :D

**Comment by weeeBox** [comment]
You need to have Scene View or Game View focused in order to get key bindings input. I've created a small test project with the same bindings and it worked fine. We can try screen share to troubleshoot

**Comment by dragutux** [comment]
add me to skype ^^ (same nick as here)

**Comment by SpaceCadetRen** [comment]
I have internet issues: on a phone with provider tech support/ Lets
schedulr for tomorrow. What's your timezone?

**Comment by dragutux** [comment]
gmt+2 but i am often there at weird times, best will be to pm me on skype or here ^^ usually i start my day around 2pm

**Comment by dragutux** [comment]
updating : we probably got this fixed by @weeeBox :) now the variables/bind dont get called from the real game, that could change ? because as i explained, it opens world for changing all events based on logic on keypress.

example : e/f/<use> (button config from input) launch a raycast local check in front of player, returns status of the objects, allows for changing it etc, steal disable / enable can be extended quite easily.

enough of me spamming i'll let @weeeBox do the announcements testing etc :P but the bug i found is dead apparently, confirmed on angrybot test.
