### ISSUE TITLE
ResolveVariables increases time to enter Play Mode

### ISSUE THREAD

**Issue by brzGatsu** [SpaceMadness/lunar-unity-plugin#9]
Wrong repo, can be deleted

**Comment by weeeBox** [comment]
Hey @brzGatsu,

I can probably move it to secondary thread. You may also want to open issues in this project instead: https://github.com/spaceMadness/lunar-unity-console

**Comment by brzGatsu** [comment]
Oh, sorry about that. Will re-open in the other repo.
